name: Testing Pipeline
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-18.04
    steps:
      - run |
        echo "Test Job"
        python index.py
