name: Testing Pipeline
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install open-ssh Client
        run: which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Decrypt pem file
        env:
          SECRET_KEY_PASSPHRASE: ${{ secrets.SECRET_KEY_PASSPHRASE }}
        run: |
          chmod +x ./decrypt_secret.sh
          ./decrypt_secret.sh
      - name: Run Deploy Script
        env:
          DEPLOY_SERVERS: ${{ secrets.DEPLOY_SERVERS }}
        run: bash ./deploy/deploy.sh
