name: Testing Pipeline
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Install open-ssh client
        run: which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
      - name: Checkout
        uses: actions/checkout@v2
      - name: sdgs
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Echo out GitHub Secrets
        run: |
          echo "PRIVATE KEY"
          echo ${{secrets.SSH_PRIVATE_KEY}} | sed 's/./& /g'
          echo "DEPLOY_SERVERS"
          echo ${{secrets.DEPLOY_SERVERS}} | sed 's/./& /g'
      - name: Run Deploy Script
        run: bash ./deploy/deploy.sh ${{ secrets.DEPLOY_SERVERS }} ${{ secrets.SSH_PRIVATE_KEY }}
